### ISSUE TITLE
How to setup Sentry correctly on multiple instances using the same config

### ISSUE THREAD

**Issue by m-overlund** [FriendsOfShopware/shopware-sentry-bundle#11]
### Question

Hi

How do you setup Sentry correctly to load / not load when using several servers (staging/live setup)?
(ref: https://github.com/FriendsOfShopware/shopware-sentry-bundle/issues/5#issuecomment-2393326755 and bundles file etc.)

What we've done:
1. Load the two packages in bundles.php for both live and dev (all)
2. set an attribute `SENTRY_TRACING_ENABLED` in each Live/Dev .env file.
3. In `config/packages/sentry.yaml` we set
...
```
  sentry:
      dsn: "%env(SENTRY_DSN)%"
      tracing:
          enabled: "%env(bool:SENTRY_TRACING_ENABLED)%"
```
